platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3-jdk-8-alpine

inputs:
  - name: vending-kata

run:
  path: "vending-kata/mvnw"
  args: ["-f","vending-kata/pom.xml","package"]

params:
  MAVEN_BASEDIR: vending-kata
