platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3-jdk-8-alpine

inputs:
  - name: vending-kata

run:
  path: "./mvnw"
  args: ["versions:set",-DnewVersion=$PACKAGE_VERSION, "-DgenerateBackupPoms=false","test","package"]
  dir: vending-kata

params:
  PACKAGE_VERSION: $(cat VERSION)
