platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3-jdk-8-alpine

inputs:
  - name: vending-kata

run:
  path: "vending-kata/mvnw"
  args: ["test","package"]

params:
  MAVEN_BASEDIR: vending-kata
